// <auto-generated />
using System;
using DataIntegrityTool.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataIntegrityTool.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataIntegrityTool.Schema.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AesKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Tools")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UsageSince")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.LicenseInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LicenseInterval", (string)null);
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.LicenseMetered", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeBegun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LicenseMetered", (string)null);
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Licensetype")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToolType")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.SessionTransition", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ErrorCode")
                        .HasColumnType("integer");

                    b.Property<int>("FrameOrdinal")
                        .HasColumnType("integer");

                    b.Property<int>("LayerOrdinal")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.ToTable("SessionTransition", (string)null);
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.ToolParameters", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<byte[]>("AesKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("MinimumInterval")
                        .HasColumnType("integer");

                    b.Property<byte[]>("privateKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("publicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("usageSince")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ToolParameters", (string)null);
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.UserRegistration", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Tools")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.ToTable("UserRegistration", (string)null);
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AesKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LicensingIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("LicensingMeteredCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Tools")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.UsersAwaitingMFA", b =>
                {
                    b.HasBaseType("DataIntegrityTool.Schema.Users");

                    b.Property<int>("MFA")
                        .HasColumnType("integer");

                    b.ToTable("UsersAwaitingMFA", (string)null);
                });

            modelBuilder.Entity("DataIntegrityTool.Schema.UsersAwaitingMFA", b =>
                {
                    b.HasOne("DataIntegrityTool.Schema.Users", null)
                        .WithOne()
                        .HasForeignKey("DataIntegrityTool.Schema.UsersAwaitingMFA", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
